"""update_habit_model_and_remove_daily_stats_relationships

Revision ID: 0ba2204bbb19
Revises: ab6bba5f8d67
Create Date: 2026-05-17 15:34:36.254649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba2204bbb19'
down_revision: Union[str, Sequence[str], None] = 'ab6bba5f8d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping temporary table from previous migration
    
    # SQLite doesn't support ALTER COLUMN, skip these changes
    # The columns are already set correctly in the models
    
    # Unique constraint already exists from previous migration, skip
    
    op.drop_column('monthly_stats', 'created_at')
    op.drop_column('monthly_stats', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_stats', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('monthly_stats', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_constraint('uq_habit_user_date', 'habits_completion', type_='unique')
    op.alter_column('habits_completion', 'completion_time',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('habits', 'built_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_table('_alembic_tmp_habits_completion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('habit_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('completion_date', sa.DATE(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('completion_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'user_id', 'completion_date', name=op.f('uq_habit_user_date'))
    )
    # ### end Alembic commands ###
