"""Add password reset token table

Revision ID: 1318921ea00d
Revises: add_email_and_verified
Create Date: 2026-06-22 18:08:53.684897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1318921ea00d'
down_revision: Union[str, Sequence[str], None] = 'add_email_and_verified'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

"""
Migration notes:
This migration contains ALTER COLUMN operations that are compatible with PostgreSQL
but not SQLite. Since local development uses SQLite and production uses PostgreSQL,
these operations are commented out for local development. The changes have already
been applied to the production database, so no action is needed there.
"""
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Constraint uq_analytics_user_habit_date already exists in production
    # op.create_unique_constraint('uq_analytics_user_habit_date', 'habit_analytics', ['user_id', 'habit_id', 'date'])
    op.alter_column('habits', 'built_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('habits_completion', 'completion_time',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # Constraint uq_habit_user_date already exists in production
    # op.create_unique_constraint('uq_habit_user_date', 'habits_completion', ['habit_id', 'user_id', 'completion_date'])
    # Email column already has nullable=False in production
    # op.alter_column('users', 'email',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Email column already has nullable=False in production
    # op.alter_column('users', 'email',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # Constraint uq_habit_user_date already exists in production
    # op.drop_constraint('uq_habit_user_date', 'habits_completion', type_='unique')
    op.alter_column('habits_completion', 'completion_time',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('habits', 'built_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # Constraint uq_analytics_user_habit_date already exists in production
    # op.drop_constraint('uq_analytics_user_habit_date', 'habit_analytics', type_='unique')
    # ### end Alembic commands ###
