"""Add last_logout field to users

Revision ID: 14a141d14cc9
Revises: 1318921ea00d
Create Date: 2026-07-01 16:56:28.234744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a141d14cc9'
down_revision: Union[str, Sequence[str], None] = '1318921ea00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_habit_date'), 'habit_analytics', type_='unique')
    op.create_unique_constraint('uq_analytics_user_habit_date', 'habit_analytics', ['user_id', 'habit_id', 'date'])
    op.alter_column('habits', 'built_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('habits_completion', 'completion_time',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_habit_user_date', 'habits_completion', ['habit_id', 'user_id', 'completion_date'])
    op.add_column('users', sa.Column('last_logout', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'last_logout')
    op.drop_constraint('uq_habit_user_date', 'habits_completion', type_='unique')
    op.alter_column('habits_completion', 'completion_time',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('habits', 'built_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint('uq_analytics_user_habit_date', 'habit_analytics', type_='unique')
    op.create_unique_constraint(op.f('uq_user_habit_date'), 'habit_analytics', ['user_id', 'habit_id', 'date'])
    # ### end Alembic commands ###
