"""add_user_preferences

Revision ID: 16798955c587
Revises: 4d4ac00ba833
Create Date: 2026-07-02 15:21:37.384229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16798955c587'
down_revision: Union[str, Sequence[str], None] = '4d4ac00ba833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Comment out operations already applied in production
    # op.drop_index(op.f('ix_daily_stats_id'), table_name='daily_stats')
    # op.drop_table('daily_stats')
    # op.alter_column('habits', 'built_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('habits_completion', 'completion_time',
    #            existing_type=sa.TIMESTAMP(),
    #            type_=sa.DateTime(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.create_index(op.f('ix_habits_completion_id'), 'habits_completion', ['id'], unique=False)
    # op.create_unique_constraint('uq_habit_user_date', 'habits_completion', ['habit_id', 'user_id', 'completion_date'])
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('theme', sa.String(), nullable=True))
    # op.alter_column('users', 'email',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Comment out operations already applied in production
    # op.alter_column('users', 'email',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    op.drop_column('users', 'theme')
    op.drop_column('users', 'language')
    # op.drop_constraint('uq_habit_user_date', 'habits_completion', type_='unique')
    # op.drop_index(op.f('ix_habits_completion_id'), table_name='habits_completion')
    # op.alter_column('habits_completion', 'completion_time',
    #            existing_type=sa.DateTime(),
    #            type_=sa.TIMESTAMP(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('habits', 'built_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.create_table('daily_stats',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=False),
    # sa.Column('habit_id', sa.INTEGER(), nullable=False),
    # sa.Column('date', sa.DATE(), nullable=False),
    # sa.Column('completions', sa.INTEGER(), nullable=True),
    # sa.Column('completion_rate', sa.FLOAT(), nullable=True),
    # sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('user_id', 'habit_id', 'date', name=op.f('uq_user_habit_date'))
    # )
    # op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    # ### end Alembic commands ###
