"""add_unique_constraint_to_habits_completion

Revision ID: 3bf07c7c4720
Revises: 50d80e4b9a39
Create Date: 2026-06-01 14:20:53.709285

"""
from typing import Sequence, Union
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3bf07c7c4720'
down_revision: Union[str, Sequence[str], None] = '50d80e4b9a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove duplicate completions before adding unique constraint
    from sqlalchemy import text
    conn = op.get_bind()
    
    # Delete duplicates, keeping only the first one
    conn.execute(text('''
        DELETE FROM habits_completion 
        WHERE id NOT IN (
            SELECT MIN(id) 
            FROM habits_completion 
            GROUP BY habit_id, user_id, completion_date
        )
    '''))
    
    # Add unique constraint
    try:
        conn.execute(text('ALTER TABLE habits_completion ADD CONSTRAINT uq_habit_user_date UNIQUE (habit_id, user_id, completion_date)'))
        print("Unique constraint added successfully")
    except Exception as e:
        print(f"Error adding unique constraint: {e}")
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import text
    conn = op.get_bind()
    try:
        conn.execute(text('ALTER TABLE habits_completion DROP CONSTRAINT uq_habit_user_date'))
    except Exception:
        # Constraint might not exist
        pass
    # ### end Alembic commands ###
