"""add_unique_constraint_to_habits_completion

Revision ID: 3bf07c7c4720
Revises: 50d80e4b9a39
Create Date: 2026-06-01 14:20:53.709285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf07c7c4720'
down_revision: Union[str, Sequence[str], None] = '50d80e4b9a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint to prevent duplicate completions
    # PostgreSQL-specific
    from sqlalchemy import text
    conn = op.get_bind()
    try:
        conn.execute(text('ALTER TABLE habits_completion ADD CONSTRAINT uq_habit_user_date UNIQUE (habit_id, user_id, completion_date)'))
    except Exception as e:
        print(f"Error adding unique constraint: {e}")
        # Constraint might already exist
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import text
    conn = op.get_bind()
    try:
        conn.execute(text('ALTER TABLE habits_completion DROP CONSTRAINT uq_habit_user_date'))
    except Exception:
        # Constraint might not exist
        pass
    # ### end Alembic commands ###
