"""add_autoincrement_to_id_columns

Revision ID: 50d80e4b9a39
Revises: 7202e1f54521
Create Date: 2026-06-01 13:58:32.296150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d80e4b9a39'
down_revision: Union[str, Sequence[str], None] = '7202e1f54521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create sequences for auto-increment if they don't exist
    op.execute('CREATE SEQUENCE IF NOT EXISTS users_id_seq')
    op.execute('CREATE SEQUENCE IF NOT EXISTS habits_id_seq')
    op.execute('CREATE SEQUENCE IF NOT EXISTS habits_completion_id_seq')
    
    # Set sequences as owned by the tables
    op.execute('ALTER SEQUENCE users_id_seq OWNED BY users.id')
    op.execute('ALTER SEQUENCE habits_id_seq OWNED BY habits.id')
    op.execute('ALTER SEQUENCE habits_completion_id_seq OWNED BY habits_completion.id')
    
    # Set default values
    op.execute('ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval(\'users_id_seq\')')
    op.execute('ALTER TABLE habits ALTER COLUMN id SET DEFAULT nextval(\'habits_id_seq\')')
    op.execute('ALTER TABLE habits_completion ALTER COLUMN id SET DEFAULT nextval(\'habits_completion_id_seq\')')
    
    # Add unique constraint if it doesn't exist
    op.execute('ALTER TABLE habits_completion ADD CONSTRAINT IF NOT EXISTS uq_habit_user_date UNIQUE (habit_id, user_id, completion_date)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE habits_completion DROP CONSTRAINT IF EXISTS uq_habit_user_date')
    op.execute('ALTER TABLE users ALTER COLUMN id DROP DEFAULT')
    op.execute('ALTER TABLE habits ALTER COLUMN id DROP DEFAULT')
    op.execute('ALTER TABLE habits_completion ALTER COLUMN id DROP DEFAULT')
    
    op.execute('DROP SEQUENCE IF EXISTS users_id_seq')
    op.execute('DROP SEQUENCE IF EXISTS habits_id_seq')
    op.execute('DROP SEQUENCE IF EXISTS habits_completion_id_seq')
    # ### end Alembic commands ###
