"""add_autoincrement_to_id_columns

Revision ID: 50d80e4b9a39
Revises: 7202e1f54521
Create Date: 2026-06-01 13:58:32.296150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d80e4b9a39'
down_revision: Union[str, Sequence[str], None] = '7202e1f54521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping _alembic_tmp_habits_completion - doesn't exist in production
    op.drop_constraint(op.f('uq_user_habit_date'), 'habit_analytics', type_='unique')
    op.create_unique_constraint('uq_analytics_user_habit_date', 'habit_analytics', ['user_id', 'habit_id', 'date'])
    op.alter_column('habits', 'built_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('habits_completion', 'completion_time',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_unique_constraint('uq_habit_user_date', 'habits_completion', ['habit_id', 'user_id', 'completion_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_habit_user_date', 'habits_completion', type_='unique')
    op.alter_column('habits_completion', 'completion_time',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('habits', 'built_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint('uq_analytics_user_habit_date', 'habit_analytics', type_='unique')
    op.create_unique_constraint(op.f('uq_user_habit_date'), 'habit_analytics', ['user_id', 'habit_id', 'date'])
    op.create_table('_alembic_tmp_habits_completion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('habit_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('completion_date', sa.DATE(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('completion_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'user_id', 'completion_date', name=op.f('uq_habit_user_date'))
    )
    # ### end Alembic commands ###
