"""add_autoincrement_to_id_columns

Revision ID: 50d80e4b9a39
Revises: 7202e1f54521
Create Date: 2026-06-01 13:58:32.296150

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '50d80e4b9a39'
down_revision: Union[str, Sequence[str], None] = '7202e1f54521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL-specific: sequences for auto-increment
    # Skip for SQLite (local development)
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
