"""fix_unique_constraint_duplicates

Revision ID: 9a12a30a2e8f
Revises: 3bf07c7c4720
Create Date: 2026-06-01 14:29:37.152589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a12a30a2e8f'
down_revision: Union[str, Sequence[str], None] = '3bf07c7c4720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove duplicate completions and add unique constraint
    from sqlalchemy import text
    conn = op.get_bind()
    
    # Delete duplicates, keeping only the first one
    conn.execute(text('''
        DELETE FROM habits_completion 
        WHERE id NOT IN (
            SELECT MIN(id) 
            FROM habits_completion 
            GROUP BY habit_id, user_id, completion_date
        )
    '''))
    
    # Drop existing constraint if it exists
    try:
        conn.execute(text('ALTER TABLE habits_completion DROP CONSTRAINT IF EXISTS uq_habit_user_date'))
    except Exception:
        pass
    
    # Add unique constraint
    conn.execute(text('ALTER TABLE habits_completion ADD CONSTRAINT uq_habit_user_date UNIQUE (habit_id, user_id, completion_date)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import text
    conn = op.get_bind()
    try:
        conn.execute(text('ALTER TABLE habits_completion DROP CONSTRAINT uq_habit_user_date'))
    except Exception:
        pass
    # ### end Alembic commands ###
