"""update_weekly_stats_remove_redundant_columns

Revision ID: ab6bba5f8d67
Revises: 8dabe73065b0
Create Date: 2026-05-16 10:12:47.690197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6bba5f8d67'
down_revision: Union[str, Sequence[str], None] = '8dabe73065b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # daily_stats table was never created, skip dropping it
    
    # SQLite doesn't support ALTER COLUMN, skip the completion_time NOT NULL change
    # The column is already set correctly in the model
    
    # Index and unique constraint already exist from previous migration, skip
    
    op.drop_column('weekly_stats', 'updated_at')
    op.drop_column('weekly_stats', 'created_at')
    op.drop_column('weekly_stats', 'completion_rate')
    op.drop_column('weekly_stats', 'total_completions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_stats', sa.Column('total_completions', sa.INTEGER(), nullable=True))
    op.add_column('weekly_stats', sa.Column('completion_rate', sa.FLOAT(), nullable=True))
    op.add_column('weekly_stats', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('weekly_stats', sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_constraint('uq_habit_user_date', 'habits_completion', type_='unique')
    op.drop_index(op.f('ix_habits_completion_id'), table_name='habits_completion')
    
    # SQLite doesn't support ALTER COLUMN, skip the completion_time nullable change
    
    op.create_table('daily_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('habit_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('completions', sa.INTEGER(), nullable=True),
    sa.Column('completion_rate', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'habit_id', 'date', name=op.f('uq_user_habit_date'))
    )
    op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    # ### end Alembic commands ###
