"""rename_streak_to_current_streak

Revision ID: e970c1223abd
Revises: df3561f83cce
Create Date: 2026-04-29 10:21:52.958310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e970c1223abd'
down_revision: Union[str, Sequence[str], None] = 'df3561f83cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_analytics', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.drop_column('habit_analytics', 'streak')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_analytics', sa.Column('streak', sa.INTEGER(), nullable=True))
    op.drop_column('habit_analytics', 'current_streak')
    # ### end Alembic commands ###
